import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { poppins } from "./fonts";

export const metadata: Metadata = {
  title: {
    template: '%s | Acme',
    default: 'Acme'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased font-poppins ${poppins.variable}`}
    >
      <body className="min-h-full flex flex-col px-16">
        <Navbar />
        <main className="py-4 min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
